//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIC.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleApartado
    {
        public int IdDetalleApartado { get; set; }
        public int IdApartado { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Sku { get; set; }
        public string NombreProducto { get; set; }
        public double Precio { get; set; }
        public double Total { get; set; }
    
        public virtual Apartado Apartado { get; set; }
    }
}
