//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIC.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public int IdDetalle_Factura { get; set; }
        public int IdFactura { get; set; }
        public int Cantidad { get; set; }
        public string Sku { get; set; }
        public string NombreProducto { get; set; }
        public double Precio { get; set; }
        public double Total { get; set; }
    
        public virtual Factura Factura { get; set; }
    }
}
