//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIC.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.DetalleFactura = new HashSet<DetalleFactura>();
            this.PagoFactura = new HashSet<PagoFactura>();
        }
    
        public int IdFactura { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public double SubTotal { get; set; }
        public double GranTotal { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public double Descuento { get; set; }
        public int IdVendedor { get; set; }
        public string NumFactura { get; set; }
        public double TasaCambio { get; set; }
        public bool Anulado { get; set; }
        public double IVA { get; set; }
        public string IdSacursal { get; set; }
        public string Moneda { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoFactura> PagoFactura { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
