//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIC.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastosOrganizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GastosOrganizacion()
        {
            this.Gasto = new HashSet<Gasto>();
        }
    
        public int IdGastosOrganizacion { get; set; }
        public double Valor { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdGasto { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime CreadoUTC { get; set; }
        public System.DateTime ModificadoUTC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gasto> Gasto { get; set; }
    }
}
