//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIC.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moneda
    {
        public int IdMoneda { get; set; }
        public string Nombre { get; set; }
        public Nullable<double> Valor { get; set; }
        public bool Eliminado { get; set; }
        public System.DateTime CreadoUTC { get; set; }
        public System.DateTime ModificadoUTC { get; set; }
    }
}
