//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIC.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoRecibo
    {
        public int IdPagoRecibo { get; set; }
        public int IdRecibo { get; set; }
        public int IdMetodoDePago { get; set; }
        public double Pagado { get; set; }
    
        public virtual MetodoPago MetodoPago { get; set; }
        public virtual Recibo Recibo { get; set; }
    }
}
