//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIC.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recibo()
        {
            this.PagoRecibo = new HashSet<PagoRecibo>();
        }
    
        public int IdRecibo { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public int IdApartado { get; set; }
        public double Cuota { get; set; }
        public double IVA { get; set; }
        public bool Anulado { get; set; }
        public double Tasa { get; set; }
    
        public virtual Apartado Apartado { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoRecibo> PagoRecibo { get; set; }
    }
}
